version: '3.8'
services:
  opensearch-node1:
    build:
      context: . # 현재 디렉토리를 컨텍스트로 사용
      dockerfile: docker/Dockerfile # 사용할 Dockerfile 지정
    image: opensearch-node1:2.15.0 # 빌드된 이미지를 명시적으로 태그 지정
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # 클러스터 이름 지정
      - node.name=opensearch-node1 # 이 컨테이너에서 실행될 노드 이름 지정
      - discovery.type=single-node # 단일 노드 설정 (테스트 환경)
      - bootstrap.memory_lock=true # JVM 힙 메모리 스와핑 비활성화
      - OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g # JVM 힙 메모리를 최대 4GB로 설정
      - DISABLE_INSTALL_DEMO_CONFIG=true # 데모 구성 설치 방지
      - DISABLE_SECURITY_PLUGIN=true # 보안 플러그인 비활성화
      - logger.level=INFO # 로그 레벨 설정
      - OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT:-http://opensearch-node1:9200} # 환경 변수로 엔드포인트 설정
    ulimits:
      memlock:
        soft: -1 # memlock을 무제한으로 설정 (소프트 또는 하드 제한 없음)
        hard: -1
      nofile:
        soft: 65536 # opensearch 사용자의 최대 오픈 파일 수 - 최소 65536으로 설정
        hard: 65536
    volumes:
      - ./init:/usr/share/opensearch/init:rw # 초기화 스크립트와 매핑 파일을 포함하는 디렉토리, 읽기 쓰기 전용으로 마운트
      - opensearch-data1:/usr/share/opensearch/data # 데이터 지속성을 위한 볼륨
    ports:
      - "${OPENSEARCH_PORT:-9200}:9200" # REST API, 환경 변수로 포트 설정 가능
      - "${PERFORMANCE_ANALYZER_PORT:-9600}:9600" # Performance Analyzer
    expose:
      - "9200"
      - "9600"
    networks:
      - opensearch-net # 모든 컨테이너가 동일한 Docker 브리지 네트워크에 연결
    healthcheck:
      test: ["CMD-SHELL", "curl -s -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    command: |
      /bin/bash -c "
      ls -l /usr/share/opensearch/init/
      file /usr/share/opensearch/init/init-opensearch.sh
      /usr/share/opensearch/opensearch-docker-entrypoint.sh &
      sleep 30
      bash -x /usr/share/opensearch/init/init-opensearch.sh
      tail -f /dev/null
      "

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.15.0 # 특정 버전 사용
    container_name: opensearch-dashboards
    ports:
      - "${DASHBOARDS_PORT:-5601}:5601" # 호스트 포트를 환경 변수로 설정 가능
    expose:
      - "5601" # OpenSearch Dashboards 웹 접근을 위해 포트 5601 노출
    environment:
      - OPENSEARCH_HOSTS=http://opensearch-node1:9200 # OpenSearch 노드 주소 설정
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true # OpenSearch Dashboards의 보안 대시보드 플러그인 비활성화
    networks:
      - opensearch-net
    depends_on:
      opensearch-node1:
        condition: service_healthy

volumes:
  opensearch-data1:
    driver: local # 명시적으로 로컬 드라이버 지정

networks:
  opensearch-net:
    driver: bridge # 명시적으로 브리지 네트워크 지정
