#apiVersion: k6.io/v1alpha1
#kind: K6
#metadata:
#  name: k6-sample
#spec:
#  parallelism: 4
#  script:
#    configMap:
#      name: crocodile-stress-test
#      file: test.js

#apiVersion: k6.io/v1alpha1
apiVersion: v1
kind: Pod
metadata:
  name: k6-pod
spec:
  containers:
  - name: k6
    image: grafana/k6
    args: ["run", "--out", "experimental-prometheus-rw", "--tag", "testid=k6", "/scripts/test-script.js"]
    resources:
      limits:
        cpu: 256m
        memory: 1024Mi
    env:
    - name: K6_PROMETHEUS_RW_SERVER_URL
      value: "http://prometheus.monitoring.svc.cluster.local:9090/api/v1/write"
    volumeMounts:
    - name: k6-test-script
      mountPath: /scripts
  restartPolicy: Never
  volumes:
  - name: k6-test-script
    configMap:
      name: k6-test-script
